### ISSUE TITLE
Clean up AssignmentRows name

### ISSUE THREAD

**Issue by Connor-Bernard** [Connor-Bernard/gradeView#44]
The `assignmentRes` and `assignmentRows` constants in the api server file are somewhat misleading and should be renamed to some variation of `assignmentMeta`

**Comment by predatorprasad** [comment]
working on it

**Comment by predatorprasad** [comment]
I have made a PR #45 with necessary changes pls review and let me know

**Comment by Connor-Bernard** [comment]
> 

Thank you; changed up the taskMeta api response name for coherency, but that's about it.

**Comment by predatorprasad** [comment]
thank's
